services:
  app:
    image: ghcr.io/maxine-n/devops-tools-image:main
    volumes:
      - type: bind
        source: ~/.ssh/
        target: /root/.ssh/
        read_only: false
      - type: bind
        source: ~/.kube/
        target: /root/.kube/
        read_only: false
      - type: bind
        source: ~/.gitconfig
        target: /root/.gitconfig
        read_only: true
      - type: bind
        source: .
        target: /mnt
